/zhome/a1/4/145993/.lsbatch/1740232034.24164391.shell: line 15: 3422560 Killed                  python data/find_location.py
